import {
  Geist,
  Geist_Mono,
  Inter,
  Playfair_Display,
  Poppins,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Nav";
import { Analytics } from "@vercel/analytics/next";
import { Suspense } from "react";

import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure your fonts - Tailwind v4 style
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
});

// Alternative options
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${playfairDisplay.variable} ${poppins.variable} ${montserrat.variable} antialiased`}
      >
        <Suspense
          fallback={<div className="text-white p-10">Loading page...</div>}
        >
          <Navigation />
          {children}
          <Footer />
        </Suspense>
        <Analytics mode="production" />;
      </body>
    </html>
  );
}
