const celebrities = [
  {
    name: "John Doe",
    role: "TV Personality | Actor",
    image: "https://randomuser.me/api/portraits/men/16.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/16.jpg",
    feeRange: "Please Contact",
    availability: "Limited",
    yearsActive: "2010–Present",
    knownFor: "Reality TV, Talk Shows, Fashion Events",
    scrobbles: "320.1K",
    audience: "15.4K",
    bio: "John Doe is a well-known television personality and actor. He is available for special appearances and brand collaborations.",
  },
  {
    name: "Mike Smith",
    role: "Comedian | Host",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    feeRange: "$5,000–$10,000",
    availability: "Available",
    yearsActive: "2005–Present",
    knownFor: "Comedy Shows, Hosting Events, TV",
    scrobbles: "210.3K",
    audience: "18.2K",
    bio: "Mike Smith brings humor and energy to any stage. Perfect for hosting gigs, comedy nights, or media appearances.",
  },
  {
    name: "Robert Johnson",
    role: "Motivational Speaker",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/45.jpg",
    feeRange: "$8,000–$15,000",
    availability: "Please Contact",
    yearsActive: "2000–Present",
    knownFor: "Leadership Talks, Education, Empowerment",
    scrobbles: "158.2K",
    audience: "12.5K",
    bio: "Robert Johnson inspires audiences around the globe through transformative speaking engagements focused on leadership and motivation.",
  },
  {
    name: "Emily Clark",
    role: "Actress | Influencer",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/12.jpg",
    feeRange: "$10,000+",
    availability: "Inquire for Schedule",
    yearsActive: "2012–Present",
    knownFor: "Film, Fashion, Brand Collaborations",
    scrobbles: "430.0K",
    audience: "27.8K",
    bio: "Emily Clark is a rising star in film and fashion, collaborating with luxury brands and appearing at global events.",
  },
  {
    name: "Sophia Lee",
    role: "Model | Entrepreneur",
    image: "https://randomuser.me/api/portraits/women/24.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/24.jpg",
    feeRange: "$12,000–$25,000",
    availability: "Flexible",
    yearsActive: "2014–Present",
    knownFor: "Fashion, Beauty, Social Campaigns",
    scrobbles: "295.5K",
    audience: "22.1K",
    bio: "Sophia Lee is a high-profile model and entrepreneur, often seen at fashion week and representing global beauty brands.",
  },
  {
    name: "David Brown",
    role: "Sports Figure | Analyst",
    image: "https://randomuser.me/api/portraits/men/33.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/33.jpg",
    feeRange: "$20,000+",
    availability: "Limited",
    yearsActive: "1998–Present",
    knownFor: "Sports Commentary, Endorsements",
    scrobbles: "382.4K",
    audience: "19.7K",
    bio: "David Brown is a former pro-athlete and current sports analyst, available for keynote speaking and media campaigns.",
  },
  {
    name: "Olivia Wilson",
    role: "Actress | Public Speaker",
    image: "https://randomuser.me/api/portraits/women/36.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/36.jpg",
    feeRange: "$7,500–$20,000",
    availability: "Available",
    yearsActive: "2010–Present",
    knownFor: "Film, Mental Health Advocacy",
    scrobbles: "165.7K",
    audience: "14.3K",
    bio: "Olivia Wilson is known for her versatile acting and passion for mental health awareness through public speaking.",
  },
  {
    name: "James Miller",
    role: "TV Host | Entertainer",
    image: "https://randomuser.me/api/portraits/men/52.jpg",
    profileImage: "https://randomuser.me/api/portraits/men/52.jpg",
    feeRange: "$15,000–$30,000",
    availability: "Please Contact",
    yearsActive: "2001–Present",
    knownFor: "Talk Shows, Live Events, Interviews",
    scrobbles: "510.8K",
    audience: "30.9K",
    bio: "James Miller has hosted some of the most recognized TV segments and is ideal for high-profile entertainment appearances.",
  },
  {
    name: "Ava Martinez",
    role: "Celebrity | Entertainer",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    feeRange: "Please Contact",
    availability: "Open for Bookings",
    yearsActive: "Early 2000s–Present",
    knownFor: "Pop Culture, Music, Fashion, Public Appearances",
    scrobbles: "507.0K",
    audience: "41.2K",
    bio: "Ava Martinez is an internationally recognized celebrity known for her influence in entertainment and pop culture.",
  },
];

export default celebrities;
